services:
  traefik:
    image: traefik:2.9
    container_name: proxy
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=zach@steelhead.design"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    expose:
      - "22:22"
    env_file:
      - env/proxy.env
    volumes:
      - ./letsencrypt:/letsencrypt:rw
      - /var/run/docker.sock:/var/run/docker.sock
      #- ./traefik.yml:/traefik.yml:rw
    networks:
      - reverse-proxynet
    labels:
      - traefik.http.routers.http_catchall.rule=HostRegexp(`{any:.+}`) 
      - traefik.http.routers.http_catchall.entrypoints=web 
      - traefik.http.routers.http_catchall.middlewares=https_redirect
      - traefik.http.middlewares.https_redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https_redirect.redirectscheme.permanent=true  
      - traefik.http.middlewares.non_www.redirectregex.regex=^(http|https)?://(?:www\.)?(.+)
      - traefik.http.middlewares.non_www.redirectregex.replacement=https://$${2} 
      - traefik.http.middlewares.non_www.redirectregex.permanent=true
networks:
  reverse-proxynet:
    name: reverse-proxynet
